baseURL = "/"
title = ".burso"
author = "Matus Bursa"
copyright = "Copyright © 2020, Root; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
  
theme="the-roots-home"

#enableGitInfo=true
enableEmoji= true
enableRobotsTXT= true

# Syntax Highlight Options

[markup]
  defaultMarkdownHandler= "goldmark"
